<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="d50c3717-1f16-4100-9114-f0c5f47dfc55" name="wenzliu@WENZLIU-BOOK1 2017-09-06 14:05:29" runUser="REDMOND\wenzliu" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2017-09-06T14:05:29.8265500-07:00" queuing="2017-09-06T14:05:29.8265500-07:00" start="2017-09-06T14:05:25.9395282-07:00" finish="2017-09-06T14:05:31.8239488-07:00" />
  <TestSettings name="default" id="a4b86374-16cc-4f58-9452-088e075de30c">
    <Deployment runDeploymentRoot="wenzliu_WENZLIU-BOOK1 2017-09-06 14_05_29" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="8aa9dcfa-74b9-4605-ada6-400cf1f6e5a9" testId="896cb5e0-2d14-fbe4-aaea-56bff32722f7" testName="TestKeepAliveInNightWatchCSharp" computerName="WENZLIU-BOOK1" duration="00:00:02.3824322" startTime="2017-09-06T14:05:27.2307950-07:00" endTime="2017-09-06T14:05:29.6615134-07:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="8aa9dcfa-74b9-4605-ada6-400cf1f6e5a9">
      <Output>
        <ErrorInfo>
          <Message>Test method Microsoft.Falcon.ServiceProber.NightWatchTestsCSharp.KeepAliveControllerTestsCSharp.TestKeepAliveInNightWatchCSharp threw exception: 
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---&gt; System.Net.WebException: Unable to connect to the remote server ---&gt; System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:86</Message>
          <StackTrace>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)
 --- End of inner exception stack trace ---
    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
 --- End of inner exception stack trace ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Falcon.ServiceProber.NightWatchTestsCSharp.KeepAliveControllerTestsCSharp.&lt;TestKeepAliveInNightWatchCSharp&gt;d__2.MoveNext() in C:\workplace\repos\falconCoreServices\services\ServiceProber\tests\NightWatchTestsCSharp\KeepAliveControllerTestsCSharp.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="7e512a2b-4adb-447f-bfc8-05a73de19460" testId="02e22d50-426a-0569-8583-40eee715cd92" testName="TestEndToEndInNightWatchCSharp" computerName="WENZLIU-BOOK1" duration="00:00:02.0131606" startTime="2017-09-06T14:05:29.6674810-07:00" endTime="2017-09-06T14:05:31.6813201-07:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="7e512a2b-4adb-447f-bfc8-05a73de19460">
      <Output>
        <ErrorInfo>
          <Message>Test method Microsoft.Falcon.ServiceProber.NightWatchTestsCSharp.EndToEndTestControllerTestCSharp.TestEndToEndInNightWatchCSharp threw exception: 
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---&gt; System.Net.WebException: Unable to connect to the remote server ---&gt; System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:86</Message>
          <StackTrace>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)
 --- End of inner exception stack trace ---
    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
 --- End of inner exception stack trace ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Falcon.ServiceProber.NightWatchTestsCSharp.EndToEndTestControllerTestCSharp.&lt;TestEndToEndInNightWatchCSharp&gt;d__2.MoveNext() in C:\workplace\repos\falconCoreServices\services\ServiceProber\tests\NightWatchTestsCSharp\EndToEndTestControllerTestCSharp.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="TestKeepAliveInNightWatchCSharp" storage="c:\workplace\repos\falconcoreservices\services\serviceprober\tests\nightwatchtestscsharp\objd\anycpu\microsoft.falcon.serviceprober.nightwatchtestscsharp.dll" id="896cb5e0-2d14-fbe4-aaea-56bff32722f7">
      <Execution id="8aa9dcfa-74b9-4605-ada6-400cf1f6e5a9" />
      <TestMethod codeBase="C:\workplace\repos\falconCoreServices\services\ServiceProber\tests\NightWatchTestsCSharp\objd\AnyCPU\Microsoft.Falcon.ServiceProber.NightWatchTestsCSharp.dll" executorUriOfAdapter="executor://mstestadapter/v1" className="Microsoft.Falcon.ServiceProber.NightWatchTestsCSharp.KeepAliveControllerTestsCSharp" name="TestKeepAliveInNightWatchCSharp" />
    </UnitTest>
    <UnitTest name="TestEndToEndInNightWatchCSharp" storage="c:\workplace\repos\falconcoreservices\services\serviceprober\tests\nightwatchtestscsharp\objd\anycpu\microsoft.falcon.serviceprober.nightwatchtestscsharp.dll" id="02e22d50-426a-0569-8583-40eee715cd92">
      <Execution id="7e512a2b-4adb-447f-bfc8-05a73de19460" />
      <TestMethod codeBase="C:\workplace\repos\falconCoreServices\services\ServiceProber\tests\NightWatchTestsCSharp\objd\AnyCPU\Microsoft.Falcon.ServiceProber.NightWatchTestsCSharp.dll" executorUriOfAdapter="executor://mstestadapter/v1" className="Microsoft.Falcon.ServiceProber.NightWatchTestsCSharp.EndToEndTestControllerTestCSharp" name="TestEndToEndInNightWatchCSharp" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="896cb5e0-2d14-fbe4-aaea-56bff32722f7" executionId="8aa9dcfa-74b9-4605-ada6-400cf1f6e5a9" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="02e22d50-426a-0569-8583-40eee715cd92" executionId="7e512a2b-4adb-447f-bfc8-05a73de19460" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="2" executed="2" passed="0" failed="2" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
</TestRun>